### ISSUE TITLE
custom board

### ISSUE THREAD

**Issue by saeedniknami** [sleepybishop/mojo_hostmot2#3]
hello sir 
i am not familiar with mojo but instead i have spartan 6 xlx9 .
which software did you use for compile your code .
and if it is possible for you i want to contact with you and ask some question about inner working of hostmot module
if it is possible for you please contact me via whatsapp and this number +989363102830

with my best regards 
saeed niknami

**Comment by sleepybishop** [comment]
Hello, as noted in https://github.com/sleepybishop/mojo_hostmot2/blob/master/src/Makefile#L6, It's been built and tested with Xilinx Webpack ISE 14.7.
